### ISSUE TITLE
The project doesn't compile!

### ISSUE THREAD

**Issue by ghost** [feinstaub/qgit#1]
Is there anybody still maintaining this project?

**Comment by feinstaub** [comment]
I am not maintaining the project. I cloned the code from here http://repo.or.cz/w/qgit4/redivivus.git. The original author is Cristian Tibirna. I contacted him some time ago but he has not much time for the project. But if you look at the repo there I see some recent activities. I currently don't know how to what is the way to contribute there.

**Comment by hkarel** [comment]
Sorry, I made a mistake: it was necessary to create a 'pull request' to rhaschke/qgit. From Cristian  long wait for an answer, so I decided to work with Robert Haschke

**Comment by hkarel** [comment]
Please discard this pull request

**Comment by feinstaub** [comment]
I see that Robert Haschke also contributed to the presumed original repository http://repo.or.cz/w/qgit4/redivivus.git

Do you release the code from https://github.com/rhaschke/qgit to GNU/Linux distributions? It would be nice if there was some statement in the repository description that reflects your/R. Haschke's view about who is supposed to work on which repo. E.g. I ask myself if qgit is now "officially" forked?

**Comment by hkarel** [comment]
I believe that there should be one repository. Well if it was a  http://repo.or.cz/w/qgit4/redivivus.git 
But there are several problems:
1) Patches can be sent only by mail (I offered to Cristian allow third-party developers to create branches in its repository, but the idea didn't gain promotion);
2) Unfortunately, Cristian did not respond quickly (This is not a complaint, just ascertaining of the fact, I myself am often busy on the working);
3) Recently, the development of the most active leads Robert, but he also enters inaccuracies to a code. I thought it best to solve these problems directly with Robert, not through Cristian.

I hope that over time all new the improvements will pushed to the main repository (http://repo.or.cz/w/qgit4/redivivus.git)
Unfortunately, I have no concept of development for QGit. I do modifications QGit mostly out of necessity: Linux is improving internationalization, and GIT began to publish self messages in russian language, and qgit no longer understand it. 
I like QGit so I decided to try to teach him how to work correctly with utf-8 and utf-16 with no-latin characters. So far it turns out badly - QGit wins :(( .

**Comment by feinstaub** [comment]
Keep on your effort. :-) In the description of this (feinstaub clone) repo I linked to this discussion thread so that the current friction of current development model becomes more transparent.

**Comment by tibirna** [comment]
Hello

For what is worth I created an "official" github clone for qgit: https://github.com/tibirna/qgit. I'd be more than pleased (and indebted) if you all decided to use that for development coordination.

I'll try my best to be as responsive as possible, given my stringent time constraints.

An important note: the original QGit author is Marco Costalba: https://github.com/mcostalba. I'm just the "official" maintainer of the last few years.

Thanks for your understanding.
Cristian

**Comment by tibirna** [comment]
@hkarel Internationalisation of any codebase is not easy feat. IMO a first important step is deciding that we use utf-8 for any i18n task. I'm yet to find something that utf-16 and utf-32 can do that utf-8 can't. Using utf-8 ensures transparent evolution and acceptable cross-platform compatibility. 

The simplest part of the i18n job is making sure the UI uses only utf-8 strings. The hardest will be interactivity with file-system (file names). I guess, though, we can advance gradually. The most important part will be to have people with actual need for non-latin characters and, of course, writing proper unit-tests.

Thanks
Cristian

**Comment by ghost** [comment]
@tibirna 
Thanks for maintaining the project. May I know which platforms did you compile and test the project?

**Comment by tibirna** [comment]
@ghost I personally compile in Linux with gcc or clang, with qt5. It should compile in Windows. I don't have a mac, but it should work there too. If you try these two other platforms and find problems, let me know.

Oh! Please, follow the https://github.com/tibirna/qgit repo. This one seems to be inactive.

Thanks

**Comment by feinstaub** [comment]
Yes, please leave this repo now :-) -- and open further issues here: https://github.com/tibirna/qgit

I close this issue now.

**Comment by hkarel** [comment]
Colleagues, let me make a few clarifications:
1) I really did work to properly display messages received from the GIT into the format UTF-8. (The work is already done. The result is here: https://github.com/hkarel/qgit/commits/ru-lang). The essence of the work is that at the moment of receiving information from GIT perform the conversion from the format UTF-8 to UTF-16,  and continue to use only UTF-16 format.
2) The work does not affect the user interface.
3) File names are displayed correctly (in any case, the russian-language characters)
4) The main development is made on Kubuntu 14.04 LTS 64 bit, Qt 4.8.6/5.6.1
5) Right now I tried to build the project on Win7 32 bit, Qt 4.8.6. It was succeeded to build and even to launch! :)

**Comment by MartinBonner** [comment]
@tibirna : The thing that UTF-16 can do which UTF-8 can't, is "work nicely with Qt".  Given that qgit is build on Qt, that's a huge win for UTF-16.  (Personally I prefer UTF-8 for green-field development, but if you are working with Java, Windows, or Qt, there's a strong argument in favour of UTF-16.)
